### ISSUE TITLE
Reaper reaps json-as-json

### ISSUE THREAD

**Issue by rob-h-m** [smartcitiesdata/reaper#113]
@jmorris-pillar commented on [Fri Jul 19 2019](https://github.com/smartcitiesdata/discovery_api/issues/171)

As a data curator, I want to be able to define raw json ingestion
so that I can ingest complicated json quickly in the current system.

For datasets such as the MMTPA feed, we do not have adequate ways to specify its format using our existing schema and it's possible we'd be losing business value in the data by mutating it to fit our needs. As such we would like to be able to define a way to describe dataset definitions as just raw json ingestion.

AC:

- SmartCity.Dataset defines a new way to define a dataset with 1 item in its schema indicating to other applications that it should be processed as an entire document inside of that field.
- Schema filling places the full document into the single specified field
- Reaper should validate that the data items are still valid json.
- The document is ingested fully into presto into the single key as a single row
- Json can be returned from the api.

Technical Notes:

Do not use sourceFormat or sourceType to make this change.
Introduce new field with a great name
This should be played on the application that contains schema filler, which at time of writing is reaper.

**Comment by ManApart** [comment]
[More Notes](https://github.com/SmartColumbusOS/scosopedia/issues/65)

**Comment by ManApart** [comment]
More notes here:
https://github.com/SmartColumbusOS/scosopedia/issues/65
