### ISSUE TITLE
Duplicate Data

### ISSUE THREAD

**Issue by rob-h-m** [smartcitiesdata/reaper#119]
The attached file is the CEAV Shift Segments dataset, which was downloaded from the OS on 7/25.  It has been sorted by start date, and converted from JSON to CSV.

All of the rows in the download appear repeatedly - most of them are included ~23 times, but it varies.

Jeff G looked at this with me.  We downloaded data directly from the May Mobility API, and did not see duplicates.  Then we downloaded data from the OS API, and saw duplicates.

(Note, this was originally identified by Jeff Kupko, looking at the data in a CSV file that was downloaded and converted by Rob.  We have provided him with a de-duped version of the file.)

**Comment by rob-h-m** [comment]
[shift-segments 07-25-19.csv.zip](https://github.com/smartcitiesdata/reaper/files/3437343/shift-segments.07-25-19.csv.zip)

**Comment by ManApart** [comment]
Why was this closed? Was the issue resolved?
