### ISSUE TITLE
Spike: How to Improve GeoJSON Ingestion

### ISSUE THREAD

**Issue by jmorris-pillar** [smartcitiesdata/reaper#129]
We need to ingest "geometry.coordinates" in the format accepted by ST_GeometryFromText function in Presto.  Instead of ingesting GeoJSON just as a string, it needs to be brought in in the expected format this will allow us to use the geo-spacial functions that already exist in Presto.

Current Format: [[[-82.92790786534295,40.23401505738485],[-82.91566529272379,40.233713977868],[-82.91516396514058,40.240165488234425],[-82.92761158870283,40.240690067374786],[-82.92790786534295,40.23401505738485]]]

Expected Format (-82.92790786534295 40.23401505738485, -82.91566529272379 40.233713977868, -82.91516396514058 40.240165488234425, -82.92761158870283 40.240690067374786, -82.92790786534295 40.23401505738485)

Acceptance Criteria:

When I query:
SELECT ST_GeometryFromText('POLYGON(COLUMN_NAME)') FROM TABLE_NAME;

It should return:
POLYGON ((-82.92790786534295 40.23401505738485, -82.91566529272379 40.233713977868, -82.91516396514058 40.240165488234425, -82.92761158870283 40.240690067374786, -82.92790786534295 40.23401505738485))

Refinement Notes: 

1.) Card will touch 2 repos:  Reaper --> Geo Decoder and API --> Query Formatter
2.) Consider using 2 separate columns to store the data to help build towards keeping the original text format and the well-known text format. 
3.) Consider using custom Presto functions 
4.) Other options may exist.  Outcome of this card is to have a recommendation going forward.

**Comment by jdenen** [comment]
I don't consider this a bug because we never set out to fully support `ST_GeometryFromText`, etc. That said, this is a worthwhile enhancement.

**Comment by rajones-hntb** [comment]
Consider using 2 separate columns to store the data to help build towards keeping the original text format and the well-known text format.

Sukaant and Richard recommend moving this path forward after investigation into alternatives such as WFS Web Feature Service, ndjson2geojson
