### ISSUE TITLE
MMTPA data not persisted on expected cadence

### ISSUE THREAD

**Issue by abrock-accenture** [smartcitiesdata/reaper#134]
Currently there is only a single row in presto for the pivot__mmtpa dataset in production - looks like it was loaded on 8/7?

We don't know where this data is getting lost, but it's not making it into presto.  Grepping the last 7-ish days of logs for reaper for this dataset ID did not yield any results, but this may just be due to the fact that there isn't a lot of logging in that app.

It looks like we're seeing this same problem in both staging and production.

One other minor issue: the date is not a column in the table - thus it's hard to tell which date you're looking at without digging into the json data.  Is it possible to add this field to this dataset? Maybe a custom transformation?

**Comment by smillardHNTB** [comment]
Please loop @ramboyapati in on the resolution

**Comment by sukaant** [comment]
This issue resulted from integer columns in the datastore that could not support the large values in the MMTPA data.  

The plan to resolve this issue in prod for this particular dataset is the following:
- create new table with bigint columns for all integers (`pivot__mmtpa_new`)
- select * from pivot__mmtpa into pivot__mmtpa_new
- rename pivot__mmtpa to pivot__mmtpa_old
- rename pivot__mmtpa_new to pivot__mmtpa
- restart forklift to load all previously rejected data into the data store
- delete any duplicate rows of data if they should pop up

**Comment by sukaant** [comment]
For a more general fix to the issue, consider the following:

- Option 1: Update carpenter (eventually forklift) to map integer types to the bigint type in presto
  - We did some research and verified that bigints and integers in presto/hive/s3 take up the same amount of space
- Option 2: Allow data curators to specify more granular levels of int size (tinyint, smallint, integer, bigint) when they provide the schema, and have valkyrie reject data that is out of range for the specified type
- Option 3: Like option 1, let in as much data as possible, but show more statistical data about what data in the dataset is out of an expected range

We will need more discussion to choose the right direction.
