### ISSUE TITLE
Manage number of extract events persisted

### ISSUE THREAD

**Issue by jeffgrunewald** [smartcitiesdata/reaper#144]
As a platform operator
I want my streaming data to save a reasonable number of extractions
So that I don't fill up my view state with tens of thousands of identical messages

ACs
- [ ] Data extract events stored in applications' view state is capped
- [ ] Cap value is configurable

**Comment by ManApart** [comment]
When we exceed the cap, do we persist old events to a longer storage medium? If not how will we re-construct state?

**Comment by rob-h-m** [comment]
Assuming @bbalser will play this - still needs points assigned PLEEEEEASE

**Comment by jeffgrunewald** [comment]
resolved by https://github.com/bbalser/brook/pull/19
