### ISSUE TITLE
Reaper consumes file:ingest:end event

### ISSUE THREAD

**Issue by jeffgrunewald** [smartcitiesdata/reaper#145]
As the SCOS
I want my geospatial data in the most flexible format for visualizing and querying
So that my users get the best bang for their buck.

AC:
- [x] Reaper consumes file:ingest:end event when mime_type = "application/geo+json"
- [x] Reaper treats this like a geojson ingestion
- [x] Hosted shapefile data is converted to geojson and able to be previewed

Depends on odo #20

**Comment by rob-h-m** [comment]
AC's updated with new stuff from Jarred
