### ISSUE TITLE
Reaper handles topic creation failures more gracefully

### ISSUE THREAD

**Issue by bbrewer-papa-x** [smartcitiesdata/reaper#155]
It was recently discovered that when reaper has about 100 pending extractions on init, some of the extractions will fail to start because their topic create command fails (no connection to Elsa, likely due to resource contention). If anything, it should at least retry those extractions instead of permanently letting them die.

Given a pending extraction (one returned by `Reaper.Collections.Extractions.get_all_non_completed!` in `Reaper.Init`)
When the extraction for it starts and its topic creation fails
The extraction should not fail permanently (until next restart of Reaper/`Reaper.Init` gets called)

**Comment by carriebrinkley** [comment]
@jeffgrunewald is this still valuable?

**Comment by jeffgrunewald** [comment]
Still valid. PR up now https://github.com/smartcitiesdata/reaper/pull/169
