### ISSUE TITLE
Can we write directly to s3 rather than Presto insert

### ISSUE THREAD

**Issue by SSackey** [smartcitiesdata/reaper#77]
"Acceptance Criteria:
- Data is queryable using Presto once it has been inserted
- Data is converted to ORC format before insertion to s3

Tech Note:
- Write ORC file converter in Java
- Perform analysis on tables that are already large

Goals:
- Performance comparison vs. Presto insert

06-24-19: Migrated from SMRT-1390"

**Comment by jmorris-pillar** [comment]
Notes on 

Findings:

1.) We are able to put data into presto tables by merely putting json, orc, or avro files into the s3 folder
   --  A catch to this is that badly formatted orc/avro will break the whole table.
   --  Types such as booleans and timestamps seem to not get properly encoded to be read by presto

2.) We were able to create orc files by using the apache/orc project https://github.com/apache/orc 

3.) We were able to create avro tools by using the avro-tools.jar http://apache.claz.org/avro/avro-1.9.0/java/

4.) We were able to write json files (both gzipped and uncompressed) to s3 and get presto to read these records

4.) We produced a table of the performance of the different formats.  At a high level:
    - Single orc files provide the fastest query performance and the smallest size
    - The way we currently allow orc files to be created (40k for 11 days of cota) provides a slower query experience than most other options


Some performance wins (sorted by JSR):

1.) If we take batch datasets and coalesce them into a single orc file with create table as select... we get /TWO/ degrees of magnitude of read performance increases
    1b) Optimizing tables in this way also decreases the amount of time to write new records to the table, even when the table has the same amount of records
2.) This is a little more difficult with cota/ceav/streaming data, but if we could find a way to batch these together safely it would greatly improve the query/read performance of archived streaming data
3.) We could have forklift store records in json and then perform something like (1,2) above to put the data in a single orc file after ingest
