### ISSUE TITLE
Add timing before and after each critical Reaper operation

### ISSUE THREAD

**Issue by SSackey** [smartcitiesdata/reaper#78]
"As a smrt developer I would like to know the time complexity of each critical piece of reaper.

AC:
- Timing is accessible in Flair
- Relative performance can be compared between pieces of Reaper that are meaured. 

Tech Note: 
- reaper components: Mark duplicates, mark processed
- Consider ExProf as an alternative to timing

06-24-19: Migrated from SMRT-1392"

**Comment by rob-h-m** [comment]
rejected 08/14/19 by Carrie and Johnson
