### ISSUE TITLE
Make deduplication optional in dataset definition

### ISSUE THREAD

**Issue by SSackey** [smartcitiesdata/reaper#79]
"As a smrt developer I want to only deduplicate when it makes sense.

AC:
- Dataset definition defaults to false for deduplication
- Datasets are not deduplicated if not configured to be
- Other apps should not need to update (struct remains parsable)

06-24-19: Migrated from SMRT-1393"

**Comment by jeffgrunewald** [comment]
Implemented in https://github.com/smartcitiesdata/reaper/pull/90
