### ISSUE TITLE
Support host and ingest sourceTypes

### ISSUE THREAD

**Issue by jdenen** [smartcitiesdata/reaper#89]
We're going to move away from the "batch" sourceType. Instead, we'll have "ingest" and "host" types. "Ingest" is for the data we've previously considered "batch." It gets ingested into Presto.

"Host" sourceTypes are formats that won't be ingested but will be served from the data platform. Formats like Shapefile or JPG, for example.

Acceptance criteria:
- [x] Update "batch" logic to use "ingest" sourceType
- [x] Update supporting libraries and documentation
- [x] Migrate dataset definitions in Redis (update migration too)
- [x] Do not re-ingest data

**Comment by bbrewer-papa-x** [comment]
Questions for entry:
- update apps that match on `not "remote"` to match on `"ingest"` instead?
- any thoughts on best order for doing this?

**Comment by bbrewer-papa-x** [comment]
Command we ran in `egon` to update batch to ingest:
```elixir
SmartCity.Dataset.get_all!() |> Enum.filter(fn d -> d.technical.sourceType == "batch" end) |> Enum.map(fn d -> Map.put(d, :technical, %SmartCity.Dataset.Technical{d.technical | sourceType: "ingest"}) end) |> Enum.map(&SmartCity.Dataset.write/1)
```

**Comment by bbrewer-papa-x** [comment]
Austin and co. are going to run the release of actual prod code changes and the redis/egon based migration.
