### ISSUE TITLE
Check CSV rows for header values

### ISSUE THREAD

**Issue by jdenen** [smartcitiesdata/reaper#93]
To simplify the platform, we should move the CSV header check out of valkyrie and into reaper. It makes the most sense to live here.

Acceptance criteria:
* Reaper yeets header rows
* Reaper continues to process non-header rows as expected

**Comment by ManApart** [comment]
Once this card is done we should [remove valkyrie](https://github.com/smartcitiesdata/valkyrie/issues/53)
