### ISSUE TITLE
Force data into schema-compliance

### ISSUE THREAD

**Issue by jdenen** [smartcitiesdata/reaper#94]
To ensure subsequent services can operate on data safely, reaper needs to force each data message to comply with its dataset schema.

### Acceptance criteria
- [ ] Optional fields that return `nil` are coerced to match subschema
- [ ] List fields returning `nil` are coerced into an empty list

### Example
Given a schema:
```javascript
schema: [
  {
    name: "foo",
    type: "map",
    subSchema: [{name: "bar", type: "string"}]
  },
  {
    name: "baz",
    type: "list",
    itemType: "string"
  }
]
```

If the source returns `null` for these fields:
```javascript
{
  foo: null,
  baz: null
}
```

Reaper should fill in the blanks:
```javascript
{
  foo: {
    bar: null
  },
  baz: []
}
```

**Comment by ManApart** [comment]
Technical note: Forklift currently has a Schema Filler Module that does most of this work. Once this is done in reaper, it may no longer be needed in forklift and it may be worth removing related code from forklift, voltron, and valkyrie.
